---
title: 'Lab #4'
author: "WEI-XUAN HU"
date: "2024-02-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# There are some problems that I could not download the dataset successfully. Thus, we need to add this command.
options(repos = c(CRAN = "https://cloud.r-project.org"))

# To make sure all outputs are english, rather than Mandarin.
Sys.setenv(LANG = "en")
```

## 0. Read the data (sheet = Table 1) and install the requirements.

```{r}
install.packages("openxlsx")
install.packages("tidyverse")

library(openxlsx)
library(tidyverse)
library(dplyr)

un <- read.xlsx("UN_MigrantStockByOriginAndDestination_2019.xlsx", sheet = "Table 1")

```

## 1. creative cleaning

```{r}
# The data in the first six columns are irrelevant and need to be removed.
un_1 <- un[-c(1:6), ]

# Set the values in the column 'Country or area of origin' to blank. 
un_1[un_1 == "Country or area of origin"] <- NA

# Merge the first column and the second column and modify them into attribute fields.
un_1[1, ] <- paste(un_1[1, ], un_1[2, ])
un_1 <- un_1[-2,]

names(un_1) <- un_1[1, ]
# Delete the first row.
un_1 <- un_1[-1, ]
head(un_1)

```

### Until now, I think this data is not tidy enough because there is still NA,also some values are represented by classes which are not intuitive, such as Notes NA, Type of data (a) NA, and so on.


```{r}
str(un_1)

summary(un_1)

total_na <- sum(is.na(un_1))
```



















